name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '⚠️ BREAKING CHANGES ⚠️'
    labels:
      - 'pr-breaking'
  - title: 'Features/Enhancements'
    labels:
      - 'pr-feature'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'pr-bugfix'
      - 'bug'
  - title: 'Other'
    labels:
      - 'docs'
      - 'enhancement'

include-labels:
  - pr-breaking
  - pr-feature
  - enhancement
  - fix
  - pr-bugfix
  - bug
  - docs
exclude-labels:
  - pr-nochangelog
exclude-contributors:
  - github-actions
  - github-actions[bot]

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

# we are still in the 0.x phase, adjust release resolving accordingly
version-resolver:
  major:
    labels: []
      #- 'pr-breaking'
  minor:
    labels:
      - 'pr-breaking'
      #- 'pr-feature' # only up the minor version when step-cli versions change
  patch:
    labels:
      - 'pr-feature'
      - 'fix'
      - 'pr-bugfix'
      - 'bug'
      - 'enhancement'
  default: patch

template: |
  ---
  **Compatibility Note**

  Releases of this collection are compatible with their corresponding `step-cli` minor version.
  For example, collection releases `0.24.x` are compatible with step-cli `0.24.yy`
  Other versions may work, but are not supported.

  Please make sure to use the appropriate collection version for your version of the step tools.

  Breaking changes may happen between minor development releases (e.g. 0.20 -> 0.21).

  ---

  # Changes

  $CHANGES
